name: 刷课

on:
  push:
    branches: [ fix/workflow-args ]
  workflow_dispatch:    # 允许手动触发
  #schedule:
  #  - cron: "0 8 * * *"

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v3

      - name: 设置python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 安装依赖包 
        run: |
          pip install -r ./requirements.txt

      - name: Run main.py
        run: python main.py -u 15186801998 学习通账号 -p Wac597031 学习通密码 -l 129237531 #课程id，默认为心理课的










